### ISSUE TITLE
URL Encode

### ISSUE THREAD

**Issue by lucalaissue** [lucalaissue/riot-api-nodejs#1]
Encode the url before sending the request

**Comment by lucalaissue** [comment]
if you call _riotApi.getSummonerByName()_ with caps in the summoner name, callback will return _undefined_,

I'm working on it

**Comment by ZafixLRP** [comment]
Patched for SummonerName

**Comment by CoreyTrombley** [comment]
Couldn't you just `.toLowerCase()` the passed in param?

**Comment by lucalaissue** [comment]
No, there is a problem with the space and the special chars, i need to encode the request url or something like that

**Comment by CoreyTrombley** [comment]
Oh got it. So I assume typescript doesn't not have `encodeURI()`

**Comment by lucalaissue** [comment]
I don't have the time to fix it today. I'll test this tomorow.
