### ISSUE TITLE
Riot API Update (Does This Apply)

### ISSUE THREAD

**Issue by tance77** [lucalaissue/riot-api-nodejs#18]
As the landscape of the Riot Games API changes, we continually must evolve to meet the demands of this growing ecosystem. As such, we've completed a number of changes which have resulted in the deprecation of many of our older endpoints. You are receiving this email due to the size and scope of these changes, and as such we’ve chosen to extend our typical deprecation period from 30 to 90 days (Monday, July 24th, 2017).

We encourage you to read the deprecation announcement for these changes, but here is a quick overview:
Riot Games API domain changed to *.api.riotgames.com
Standardization of all Riot Games API endpoints
Deprecation of aggregated stats endpoints
Deprecation of batch API calls

We also suggesting taking a moment to read over the announcement of the v3 endpoints. These new endpoints will be replacing the previous endpoints.

In addition to the deprecation, as part of our security updates to the API key management, we’ll be resetting all API keys that have not been regenerated between Monday, April 24th, 2017 and Monday, July 24th, 2017. All development and production projects can avoid downtime by regenerating their API key any time before July 24th.

I'm not sure if this is going to be an issue with this library if so is there going to be an update.

**Comment by lucalaissue** [comment]
Thank you mate :), yes this will be an issue with this library, i'm going to do this before the deprecation ends.

Thanks 👍

**Comment by tance77** [comment]
@lucalaissue 
Here's a friendly reminder that we're approaching the end of our 90 day deprecation period. In exactly four weeks, on Monday July 24th, we'll be removing many of our older endpoints from the API. If you haven't already, we encourage you to read the deprecation announcement for these changes, but here is a quick overview:
Riot Games API domain changed to *.api.riotgames.com
Standardization of all Riot Games API endpoints
Deprecation of aggregated stats endpoints
Deprecation of batch API calls

We also suggest taking a moment to read over the announcement of the v3 endpoints. These new endpoints will be replacing the previous endpoints.

In addition to the deprecation, as part of our security updates to the API key management, we’ll be resetting all API keys that have not been regenerated between Monday, April 24th, 2017 and Monday, July 24th, 2017. Even if your API key is prefixed with RGAPI, it will be regenerated if it wasn't regenerated within the window. All development and production projects can avoid downtime by regenerating their API key any time before July 24th.

If you have questions or concerns you can find us on the developer forums, chatting in the community discord server, or you can email us directly.

The Riot Games API Team
